//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrganismeFormation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Formations
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Formations()
        {
            this.CandidatsFormations = new HashSet<CandidatsFormations>();
        }
    
        public decimal Id { get; set; }
        public Nullable<bool> LiguePorteuse { get; set; }
        public Nullable<bool> LigueSousTraite { get; set; }
        public Nullable<System.DateTime> DateDebut { get; set; }
        public Nullable<System.DateTime> DateFin { get; set; }
        public Nullable<System.DateTime> DateLimteInscription { get; set; }
        public Nullable<System.DateTime> DateTestSelection { get; set; }
        public Nullable<decimal> NombreTotalHeures { get; set; }
        public Nullable<decimal> NbreHeureCentre { get; set; }
        public Nullable<decimal> NbrHeureStructAccueil { get; set; }
        public Nullable<decimal> TotalHeureFOAD { get; set; }
        public Nullable<decimal> HeureELearning { get; set; }
        public Nullable<decimal> TotalAutresHeures { get; set; }
        public string TypeHeureContenu { get; set; }
        public Nullable<decimal> CoutComplet { get; set; }
        public string InfoComplementaires { get; set; }
        public Nullable<decimal> HabilitationsId { get; set; }
        public Nullable<decimal> TypedeFormationsId { get; set; }
        public string NumeroSession { get; set; }
        public Nullable<decimal> IdOrganisateurpeda { get; set; }
        public Nullable<decimal> NbreHeureAutreEspace { get; set; }
        public Nullable<decimal> OrganismeId { get; set; }
        public Nullable<decimal> LieuSiNonPorteuse { get; set; }
        public Nullable<decimal> NombreUC { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CandidatsFormations> CandidatsFormations { get; set; }
        public virtual TypedeFormations TypedeFormations { get; set; }
        public virtual Habilitations Habilitations { get; set; }
        public virtual Lieux Lieux { get; set; }
        public virtual Personnel Personnel { get; set; }
        public virtual Organismes Organismes { get; set; }
    }
}
