//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrganismeFormation.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GestionOFEntities : DbContext
    {
        public GestionOFEntities()
            : base("name=GestionOFEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admin { get; set; }
        public virtual DbSet<Candidats> Candidats { get; set; }
        public virtual DbSet<CandidatsFormations> CandidatsFormations { get; set; }
        public virtual DbSet<Formations> Formations { get; set; }
        public virtual DbSet<Habilitations> Habilitations { get; set; }
        public virtual DbSet<Lieux> Lieux { get; set; }
        public virtual DbSet<Ligues> Ligues { get; set; }
        public virtual DbSet<Passages> Passages { get; set; }
        public virtual DbSet<Personnel> Personnel { get; set; }
        public virtual DbSet<PresidentOrganisme> PresidentOrganisme { get; set; }
        public virtual DbSet<Prestataires> Prestataires { get; set; }
        public virtual DbSet<Resultats> Resultats { get; set; }
        public virtual DbSet<ResultatsUC> ResultatsUC { get; set; }
        public virtual DbSet<Sexes> Sexes { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tuteurs> Tuteurs { get; set; }
        public virtual DbSet<TypedeFinancements> TypedeFinancements { get; set; }
        public virtual DbSet<TypedeFormations> TypedeFormations { get; set; }
        public virtual DbSet<Organismes> Organismes { get; set; }
        public virtual DbSet<Responsable> Responsable { get; set; }
        public virtual DbSet<ResponsableOrganisme> ResponsableOrganisme { get; set; }
    }
}
