//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrganismeFormation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Habilitations
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Habilitations()
        {
            this.Formations = new HashSet<Formations>();
        }
    
        public decimal Id { get; set; }
        public string NumeroHabilitation { get; set; }
        public Nullable<System.DateTime> DebutDateDelivrance { get; set; }
        public Nullable<System.DateTime> FinDateDelivrance { get; set; }
        public string NumeroDelivrance { get; set; }
        public string NumeroSession { get; set; }
        public Nullable<System.DateTime> DateEPMSP { get; set; }
        public Nullable<System.DateTime> DateTEP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Formations> Formations { get; set; }
    }
}
