//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrganismeFormation.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    public partial class Ligues
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ligues()
        {
            this.Organismes = new HashSet<Organismes>();
        }
    
        public decimal Id { get; set; }
        [Required]
        public string Libelle { get; set; }
        public Nullable<double> CodeLigue { get; set; }
        [Required]
        [StringLength(250)]
        [Index("LoginIdex")]
        [Index("IdAndRating", 2, IsUnique = true)]
        [DisplayName("Identifiant")]
        public string login { get; set; }
        [Required]
        [DisplayName("Mot de passe")]
        [DataType(DataType.Password)]
        public string password { get; set; }
        [Required]
        [DisplayName("Adresse Email Responsable")]
        [DataType(DataType.EmailAddress)]
        [EmailAddress]
        public string email { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Organismes> Organismes { get; set; }
    }
}
