<?xml version="1.0" encoding="utf-8"?><Database Name="GestionOF" Class="OrganismeDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=ALEXCOMPUTER;Initial Catalog=GestionOF;Persist Security Info=True;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="GestionOFConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Admin" Member="Admin">
    <Type Name="Admin">
      <Column Name="id" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Nom" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Prenom" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="login" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="password" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Association Name="Admin_Admin" Member="Admin2" ThisKey="id" OtherKey="id" Type="Admin" Cardinality="One" />
      <Association Name="Admin_Admin" Member="Admin1" ThisKey="id" OtherKey="id" Type="Admin" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.UtilisateursLiguesDroits" Member="UtilisateursLiguesDroits">
    <Type Name="UtilisateursLiguesDroits">
      <Column Name="Id" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdUtilisateur" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="IdLigue" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="Niveau" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Association Name="Ligues_UtilisateursLiguesDroits" Member="Ligues" ThisKey="IdLigue" OtherKey="Id" Type="Ligues" IsForeignKey="true" />
      <Association Name="Utilisateurs_UtilisateursLiguesDroits" Member="Utilisateurs" ThisKey="IdUtilisateur" OtherKey="Id" Type="Utilisateurs" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Candidats" Member="Candidats">
    <Type Name="Candidats">
      <Column Name="Id" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nom" Type="System.String" DbType="Char(50)" CanBeNull="true" />
      <Column Name="Prenom" Type="System.String" DbType="Char(50)" CanBeNull="true" />
      <Column Name="NumeroLicence" Type="System.String" DbType="Char(20)" CanBeNull="true" />
      <Column Name="Telephone" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="Char(100)" CanBeNull="true" />
      <Column Name="SexeId" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Association Name="Candidats_CandidatsFormations" Member="CandidatsFormations" ThisKey="Id" OtherKey="CandidatsId" Type="CandidatsFormations" />
      <Association Name="Sexes_Candidats" Member="Sexes" ThisKey="SexeId" OtherKey="Id" Type="Sexes" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CandidatsFormations" Member="CandidatsFormations">
    <Type Name="CandidatsFormations">
      <Column Name="Id" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FormationId" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Grade" Type="System.String" DbType="Char(20)" CanBeNull="true" />
      <Column Name="StructureAccueil" Type="System.String" DbType="Char(100)" CanBeNull="true" />
      <Column Name="DetailsFinancement" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="CoutFormation" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="CandidatsId" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="TuteursId" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="TypedeFinancementsId" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Nom" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="Prenom" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="NumeroLicence" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="Telephone" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="SexeId" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Association Name="CandidatsFormations_Resultats" Member="Resultats" ThisKey="Id" OtherKey="CandidatFormationId" Type="Resultats" />
      <Association Name="Candidats_CandidatsFormations" Member="Candidats" ThisKey="CandidatsId" OtherKey="Id" Type="Candidats" IsForeignKey="true" />
      <Association Name="Formations_CandidatsFormations" Member="Formations" ThisKey="FormationId" OtherKey="Id" Type="Formations" IsForeignKey="true" />
      <Association Name="Sexes_CandidatsFormations" Member="Sexes" ThisKey="SexeId" OtherKey="Id" Type="Sexes" IsForeignKey="true" />
      <Association Name="Tuteurs_CandidatsFormations" Member="Tuteurs" ThisKey="TuteursId" OtherKey="Id" Type="Tuteurs" IsForeignKey="true" />
      <Association Name="TypedeFinancements_CandidatsFormations" Member="TypedeFinancements" ThisKey="TypedeFinancementsId" OtherKey="Id" Type="TypedeFinancements" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Formations" Member="Formations">
    <Type Name="Formations">
      <Column Name="Id" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="LiguePorteuse" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="LigueSousTraite" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="DateDebut" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="DateFin" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="DateLimteInscription" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="DateTestSelection" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="NombreTotalHeures" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="NbreHeureCentre" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="NbrHeureStructAccueil" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="TotalHeureFOAD" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="HeureELearning" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="TotalAutresHeures" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="TypeHeureContenu" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="CoutComplet" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="InfoComplementaires" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="HabilitationsId" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="PorteursId" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="PrestatairesId" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="TypedeFormationsId" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="NumeroSession" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="IdOrganisateurpeda" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="NbreHeureAutreEspace" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="OrganismeId" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Association Name="Formations_CandidatsFormations" Member="CandidatsFormations" ThisKey="Id" OtherKey="FormationId" Type="CandidatsFormations" />
      <Association Name="Formations_FormationsLieux" Member="FormationsLieux" ThisKey="Id" OtherKey="IdFormation" Type="FormationsLieux" />
      <Association Name="Formations_Lieux" Member="Lieux" ThisKey="Id" OtherKey="LieuFormationId" Type="Lieux" />
      <Association Name="Habilitations_Formations" Member="Habilitations" ThisKey="HabilitationsId" OtherKey="Id" Type="Habilitations" IsForeignKey="true" />
      <Association Name="Organismes_Formations" Member="Organismes" ThisKey="OrganismeId" OtherKey="Id" Type="Organismes" IsForeignKey="true" />
      <Association Name="Personnel_Formations" Member="Personnel" ThisKey="IdOrganisateurpeda" OtherKey="Id" Type="Personnel" IsForeignKey="true" />
      <Association Name="Porteurs_Formations" Member="Porteurs" ThisKey="PorteursId" OtherKey="Id" Type="Porteurs" IsForeignKey="true" />
      <Association Name="Prestataires_Formations" Member="Prestataires" ThisKey="PrestatairesId" OtherKey="Id" Type="Prestataires" IsForeignKey="true" />
      <Association Name="TypedeFormations_Formations" Member="TypedeFormations" ThisKey="TypedeFormationsId" OtherKey="Id" Type="TypedeFormations" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.FormationsLieux" Member="FormationsLieux">
    <Type Name="FormationsLieux">
      <Column Name="Id" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdFormation" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="IdLieu" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Association Name="Formations_FormationsLieux" Member="Formations" ThisKey="IdFormation" OtherKey="Id" Type="Formations" IsForeignKey="true" />
      <Association Name="Lieux_FormationsLieux" Member="Lieux" ThisKey="IdLieu" OtherKey="Id" Type="Lieux" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Habilitations" Member="Habilitations">
    <Type Name="Habilitations">
      <Column Name="Id" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NumeroHabilitation" Type="System.String" DbType="Char(50)" CanBeNull="true" />
      <Column Name="DebutDateDelivrance" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FinDateDelivrance" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="NumeroDelivrance" Type="System.String" DbType="Char(50)" CanBeNull="true" />
      <Column Name="NumeroSession" Type="System.String" DbType="Char(50)" CanBeNull="true" />
      <Column Name="DateEPMSP" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="DateTEP" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="Habilitations_Formations" Member="Formations" ThisKey="Id" OtherKey="HabilitationsId" Type="Formations" />
    </Type>
  </Table>
  <Table Name="dbo.Lieux" Member="Lieux">
    <Type Name="Lieux">
      <Column Name="Id" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Adresse" Type="System.String" DbType="Char(100)" CanBeNull="true" />
      <Column Name="CodePostal" Type="System.String" DbType="NChar(5)" CanBeNull="true" />
      <Column Name="Ville" Type="System.String" DbType="Char(100)" CanBeNull="true" />
      <Column Name="Telephone" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="Char(100)" CanBeNull="true" />
      <Column Name="LieuFormationId" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Association Name="Lieux_FormationsLieux" Member="FormationsLieux" ThisKey="Id" OtherKey="IdLieu" Type="FormationsLieux" />
      <Association Name="Lieux_Organismes" Member="Organismes" ThisKey="Id" OtherKey="LieuxId" Type="Organismes" />
      <Association Name="Lieux_Porteurs" Member="Porteurs" ThisKey="Id" OtherKey="LieuxId" Type="Porteurs" />
      <Association Name="Lieux_Prestataires" Member="Prestataires" ThisKey="Id" OtherKey="LieuxId" Type="Prestataires" />
      <Association Name="Formations_Lieux" Member="Formations" ThisKey="LieuFormationId" OtherKey="Id" Type="Formations" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Ligues" Member="Ligues">
    <Type Name="Ligues">
      <Column Name="Id" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Libelle" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="CodeLigue" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="Ligues_UtilisateursLiguesDroits" Member="UtilisateursLiguesDroits" ThisKey="Id" OtherKey="IdLigue" Type="UtilisateursLiguesDroits" />
    </Type>
  </Table>
  <Table Name="dbo.Organisateurs" Member="Organisateurs">
    <Type Name="Organisateurs">
      <Column Name="Id" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nom" Type="System.String" DbType="Char(50) NOT NULL" CanBeNull="false" />
      <Column Name="Prenom" Type="System.String" DbType="Char(50) NOT NULL" CanBeNull="false" />
      <Column Name="Fonction" Type="System.String" DbType="Char(50)" CanBeNull="true" />
      <Column Name="Telephone" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="Char(100) NOT NULL" CanBeNull="false" />
      <Column Name="Qualite" Type="System.String" DbType="NChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Organisations" Member="Organisations">
    <Type Name="Organisations">
      <Column Name="Id" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdOrganisme" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Organismes" Member="Organismes">
    <Type Name="Organismes">
      <Column Name="Id" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Ligue" Type="System.String" DbType="Char(100)" CanBeNull="true" />
      <Column Name="Libelle" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NumeroDeclaration" Type="System.String" DbType="NChar(20)" CanBeNull="true" />
      <Column Name="AnneeDeclaration" Type="System.String" DbType="Char(4)" CanBeNull="true" />
      <Column Name="LieuxId" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="PresidentId" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="CoordinateurId" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="DirecteurId" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="ResponsableId" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Association Name="Organismes_Formations" Member="Formations" ThisKey="Id" OtherKey="OrganismeId" Type="Formations" />
      <Association Name="Lieux_Organismes" Member="Lieux" ThisKey="LieuxId" OtherKey="Id" Type="Lieux" IsForeignKey="true" />
      <Association Name="Personnel_Organismes" Member="Personnel" ThisKey="CoordinateurId" OtherKey="Id" Type="Personnel" IsForeignKey="true" />
      <Association Name="Personnel_Organismes1" Member="Personnel1" ThisKey="DirecteurId" OtherKey="Id" Type="Personnel" IsForeignKey="true" />
      <Association Name="PresidentOrganisme_Organismes" Member="PresidentOrganisme" ThisKey="PresidentId" OtherKey="Id" Type="PresidentOrganisme" IsForeignKey="true" />
      <Association Name="Responsable_Organismes" Member="Responsable" ThisKey="ResponsableId" OtherKey="Id" Type="Responsable" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Passages" Member="Passages">
    <Type Name="Passages">
      <Column Name="Id" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Libelle" Type="System.String" DbType="Char(50) NOT NULL" CanBeNull="false" />
      <Association Name="Passages_Resultats" Member="Resultats" ThisKey="Id" OtherKey="PassagesId" Type="Resultats" />
    </Type>
  </Table>
  <Table Name="dbo.Personnel" Member="Personnel">
    <Type Name="Personnel">
      <Column Name="Id" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nom" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Prenom" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Telephone" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Association Name="Personnel_Formations" Member="Formations" ThisKey="Id" OtherKey="IdOrganisateurpeda" Type="Formations" />
      <Association Name="Personnel_Organismes" Member="Organismes" ThisKey="Id" OtherKey="CoordinateurId" Type="Organismes" />
      <Association Name="Personnel_Organismes1" Member="Organismes1" ThisKey="Id" OtherKey="DirecteurId" Type="Organismes" />
    </Type>
  </Table>
  <Table Name="dbo.Porteurs" Member="Porteurs">
    <Type Name="Porteurs">
      <Column Name="Id" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Etablissement" Type="System.String" DbType="Char(60)" CanBeNull="true" />
      <Column Name="LieuxId" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Association Name="Porteurs_Formations" Member="Formations" ThisKey="Id" OtherKey="PorteursId" Type="Formations" />
      <Association Name="Lieux_Porteurs" Member="Lieux" ThisKey="LieuxId" OtherKey="Id" Type="Lieux" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PresidentOrganisme" Member="PresidentOrganisme">
    <Type Name="PresidentOrganisme">
      <Column Name="Id" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nom" Type="System.Data.Linq.Binary" DbType="VarBinary(50)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Prenom" Type="System.Data.Linq.Binary" DbType="VarBinary(50)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Telephone" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Fonction" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="PresidentOrganisme_Organismes" Member="Organismes" ThisKey="Id" OtherKey="PresidentId" Type="Organismes" />
    </Type>
  </Table>
  <Table Name="dbo.Prestataires" Member="Prestataires">
    <Type Name="Prestataires">
      <Column Name="Id" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nom" Type="System.String" DbType="Char(250)" CanBeNull="true" />
      <Column Name="MiseADispoInstallation" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="GestionPaieFormateurs" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CoPortage" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="GestionAdministrative" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Autre" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="LieuxId" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Association Name="Prestataires_Formations" Member="Formations" ThisKey="Id" OtherKey="PrestatairesId" Type="Formations" />
      <Association Name="Lieux_Prestataires" Member="Lieux" ThisKey="LieuxId" OtherKey="Id" Type="Lieux" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Responsable" Member="Responsable">
    <Type Name="Responsable">
      <Column Name="Id" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nom" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Prenom" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Licence" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Telephone" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Association Name="Responsable_Organismes" Member="Organismes" ThisKey="Id" OtherKey="ResponsableId" Type="Organismes" />
    </Type>
  </Table>
  <Table Name="dbo.Resultats" Member="Resultats">
    <Type Name="Resultats">
      <Column Name="Id" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CandidatFormationId" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="FormationValidee" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="NumeroDiplome" Type="System.String" DbType="Char(60)" CanBeNull="true" />
      <Column Name="EPEF" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="EPMSP" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="PassagesId" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="FormationTerminee" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="Abandon" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Association Name="Resultats_ResultatsUC" Member="ResultatsUC" ThisKey="Id" OtherKey="ResultatsId" Type="ResultatsUC" />
      <Association Name="CandidatsFormations_Resultats" Member="CandidatsFormations" ThisKey="CandidatFormationId" OtherKey="Id" Type="CandidatsFormations" IsForeignKey="true" />
      <Association Name="Passages_Resultats" Member="Passages" ThisKey="PassagesId" OtherKey="Id" Type="Passages" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ResultatsUC" Member="ResultatsUC">
    <Type Name="ResultatsUC">
      <Column Name="Id" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Libelle" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Resultat" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="ResultatsId" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="ResultatMax" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Association Name="Resultats_ResultatsUC" Member="Resultats" ThisKey="ResultatsId" OtherKey="Id" Type="Resultats" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Sexes" Member="Sexes">
    <Type Name="Sexes">
      <Column Name="Id" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Code" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="Libelle" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Association Name="Sexes_Candidats" Member="Candidats" ThisKey="Id" OtherKey="SexeId" Type="Candidats" />
      <Association Name="Sexes_CandidatsFormations" Member="CandidatsFormations" ThisKey="Id" OtherKey="SexeId" Type="CandidatsFormations" />
    </Type>
  </Table>
  <Table Name="dbo.Tuteurs" Member="Tuteurs">
    <Type Name="Tuteurs">
      <Column Name="Id" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Nom" Type="System.String" DbType="Char(50)" CanBeNull="true" />
      <Column Name="Prenom" Type="System.String" DbType="Char(50)" CanBeNull="true" />
      <Column Name="NumeroLicence" Type="System.String" DbType="Char(20)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="Char(100)" CanBeNull="true" />
      <Association Name="Tuteurs_CandidatsFormations" Member="CandidatsFormations" ThisKey="Id" OtherKey="TuteursId" Type="CandidatsFormations" />
    </Type>
  </Table>
  <Table Name="dbo.TypedeFinancements" Member="TypedeFinancements">
    <Type Name="TypedeFinancements">
      <Column Name="Id" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Libelle" Type="System.String" DbType="Char(20)" CanBeNull="true" />
      <Association Name="TypedeFinancements_CandidatsFormations" Member="CandidatsFormations" ThisKey="Id" OtherKey="TypedeFinancementsId" Type="CandidatsFormations" />
    </Type>
  </Table>
  <Table Name="dbo.TypedeFormations" Member="TypedeFormations">
    <Type Name="TypedeFormations">
      <Column Name="Id" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Libelle" Type="System.String" DbType="Char(40)" CanBeNull="true" />
      <Association Name="TypedeFormations_Formations" Member="Formations" ThisKey="Id" OtherKey="TypedeFormationsId" Type="Formations" />
    </Type>
  </Table>
  <Table Name="dbo.TypeOrganisateurs" Member="TypeOrganisateurs">
    <Type Name="TypeOrganisateurs">
      <Column Name="Id" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Libelle" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Utilisateurs" Member="Utilisateurs">
    <Type Name="Utilisateurs">
      <Column Name="Id" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nom" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Prenom" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UserLogin" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="MotdePasse" Type="System.String" DbType="NVarChar(8) NOT NULL" CanBeNull="false" />
      <Association Name="Utilisateurs_UtilisateursLiguesDroits" Member="UtilisateursLiguesDroits" ThisKey="Id" OtherKey="IdUtilisateur" Type="UtilisateursLiguesDroits" />
    </Type>
  </Table>
</Database>