//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrganismeFormation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Porteurs
    {
        public decimal Id { get; set; }
        public string Etablissement { get; set; }
        public Nullable<decimal> LieuxId { get; set; }
    
        public virtual Lieux Lieux { get; set; }
    }
}
