//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrganismeFormation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResponsableOrganisme
    {
        public decimal id { get; set; }
        public Nullable<decimal> ResponsableId { get; set; }
        public Nullable<decimal> OrganismeId { get; set; }
    
        public virtual Responsable Responsable { get; set; }
        public virtual Organismes Organismes { get; set; }
    }
}
