//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrganismeFormation.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ResultatUc
    {
        public decimal Id { get; set; }
        
        public Nullable<decimal> Resultat { get; set; }
        public Nullable<decimal> ResultatsId { get; set; }
        public Nullable<decimal> DescriptifUCId { get; set; }
    
        public virtual DescriptifUC DescriptifUC { get; set; }
        public virtual Resultats Resultats { get; set; }
    }
}
